// Auto-generated by OneDriveClassify on Wednesday, March 25, 2015
//    from https://api.onedrive.com/v1.0/$metadata

package com.microsoft.onedriveaccess.model;

import com.google.gson.annotations.SerializedName;

public class Hashes {

   @SerializedName("crc32Hash")
   public String Crc32Hash;
   @SerializedName("sha1Hash")
   public String Sha1Hash;

}
