// Auto-generated by OneDriveClassify on Wednesday, March 25, 2015
//    from https://api.onedrive.com/v1.0/$metadata

package com.microsoft.onedriveaccess.model;

import com.google.gson.annotations.SerializedName;

public class Identity {

   @SerializedName("displayName")
   public String DisplayName;
   @SerializedName("id")
   public String Id;

}
