// Auto-generated by OneDriveClassify on Wednesday, March 25, 2015
//    from https://api.onedrive.com/v1.0/$metadata

package com.microsoft.onedriveaccess.model;

import com.google.gson.annotations.SerializedName;

public class ItemReference {

   @SerializedName("driveId")
   public String DriveId;
   @SerializedName("id")
   public String Id;
   @SerializedName("path")
   public String Path;

}
