// Auto-generated by OneDriveClassify on Wednesday, March 25, 2015
//    from https://api.onedrive.com/v1.0/$metadata

package com.microsoft.onedriveaccess.model;

import com.google.gson.annotations.SerializedName;
import java.util.List;

public class Permission {

   @SerializedName("grantedTo")
   public IdentitySet GrantedTo;
   @SerializedName("id")
   public String Id;
   @SerializedName("invitation")
   public SharingInvitation Invitation;
   @SerializedName("inheritedFrom")
   public ItemReference InheritedFrom;
   @SerializedName("link")
   public SharingLink Link;
   @SerializedName("roles")
   public List<String> Roles;

}
