// Auto-generated by OneDriveClassify on Wednesday, March 25, 2015
//    from https://api.onedrive.com/v1.0/$metadata

package com.microsoft.onedriveaccess.model;

import com.google.gson.annotations.SerializedName;

public class Quota {

   @SerializedName("deleted")
   public Long Deleted;
   @SerializedName("remaining")
   public Long Remaining;
   @SerializedName("state")
   public String State;
   @SerializedName("total")
   public Long Total;
   @SerializedName("used")
   public Long Used;

}
