// Auto-generated by OneDriveClassify on Wednesday, March 25, 2015
//    from https://api.onedrive.com/v1.0/$metadata

package com.microsoft.onedriveaccess.model;

import com.google.gson.annotations.SerializedName;

public class ThumbnailSet {

   @SerializedName("id")
   public String Id;
   @SerializedName("large")
   public Thumbnail Large;
   @SerializedName("medium")
   public Thumbnail Medium;
   @SerializedName("small")
   public Thumbnail Small;
   @SerializedName("source")
   public Thumbnail Source;

}
