// Auto-generated by OneDriveClassify on Wednesday, March 25, 2015
//    from https://api.onedrive.com/v1.0/$metadata

package com.microsoft.onedriveaccess.model;

import com.google.gson.annotations.SerializedName;
import java.util.Date;
import java.util.List;

public class UploadSession {

   @SerializedName("uploadUrl")
   public String UploadUrl;
   @SerializedName("expirationDateTime")
   public Date ExpirationDateTime;
   @SerializedName("nextExpectedRanges")
   public List<String> NextExpectedRanges;

}
