// Auto-generated by OneDriveClassify on Wednesday, March 25, 2015
//    from https://api.onedrive.com/v1.0/$metadata

package com.microsoft.onedriveaccess.model;

import com.google.gson.annotations.SerializedName;

public class Video {

   @SerializedName("bitrate")
   public Long Bitrate;
   @SerializedName("duration")
   public Long Duration;
   @SerializedName("height")
   public Long Height;
   @SerializedName("width")
   public Long Width;

}
