/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_pwsafe_lib_crypto_SHA256Pws */

#ifndef _Included_org_pwsafe_lib_crypto_SHA256Pws
#define _Included_org_pwsafe_lib_crypto_SHA256Pws
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_pwsafe_lib_crypto_SHA256Pws
 * Method:    doDigestN
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_pwsafe_lib_crypto_SHA256Pws_digestNNative
        (JNIEnv *, jclass, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
